# Form implementation generated from reading ui file 'C:\Users\matut\Desktop\Carpetas\APUNTES\DAM-2\DI\Trimestre1\PereiraGutierrez\templates\about.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    """
    Clase de interfaz gráfica para el diálogo "Acerca de...".

    Esta clase define la interfaz gráfica para mostrar información sobre la aplicación.

    """
    def setupUi(self, dlgAbout):
        """
        Configura la interfaz gráfica del diálogo.

        :param dlgAbout: Ventana del diálogo "Acerca de...".
        :type dlgAbout: QtWidgets.QDialog

        """
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dlgAbout.resize(573, 421)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/coche2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgAbout.setWindowIcon(icon)
        dlgAbout.setStyleSheet("")
        dlgAbout.setModal(True)
        self.btnCerrarAbout = QtWidgets.QPushButton(parent=dlgAbout)
        self.btnCerrarAbout.setGeometry(QtCore.QRect(241, 370, 91, 31))
        self.btnCerrarAbout.setObjectName("btnCerrarAbout")
        self.frameAbout = QtWidgets.QFrame(parent=dlgAbout)
        self.frameAbout.setGeometry(QtCore.QRect(30, 30, 511, 321))
        self.frameAbout.setStyleSheet("")
        self.frameAbout.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frameAbout.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameAbout.setObjectName("frameAbout")
        self.label_7 = QtWidgets.QLabel(parent=self.frameAbout)
        self.label_7.setGeometry(QtCore.QRect(90, 50, 101, 101))
        self.label_7.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/img/img/coche2.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(parent=self.frameAbout)
        self.label_6.setGeometry(QtCore.QRect(90, 270, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(parent=self.frameAbout)
        self.label_3.setGeometry(QtCore.QRect(90, 190, 321, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frameAbout)
        self.label_4.setGeometry(QtCore.QRect(90, 230, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(parent=self.frameAbout)
        self.label.setGeometry(QtCore.QRect(230, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frameAbout)
        self.label_2.setGeometry(QtCore.QRect(230, 100, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.frameAbout)
        self.label_5.setGeometry(QtCore.QRect(90, 250, 371, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        """
        Traduce los textos de la interfaz gráfica del diálogo.

        :param dlgAbout: Ventana del diálogo "Acerca de...".
        :type dlgAbout: QtWidgets.QDialog

        """
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "Acerca de..."))
        self.btnCerrarAbout.setText(_translate("dlgAbout", "Cerrar"))
        self.label_6.setText(_translate("dlgAbout", "2023 - IES Teis Vigo"))
        self.label_3.setText(_translate("dlgAbout", "6/10/2023 - Lucas Matías Pereira Gutiérrez"))
        self.label_4.setText(_translate("dlgAbout", "Proyecto de fin de ciclo"))
        self.label.setText(_translate("dlgAbout", "CarTeis"))
        self.label_2.setText(_translate("dlgAbout", "Versión: 0.0.1 rc"))
        self.label_5.setText(_translate("dlgAbout", "Ciclo Superior DAM"))
