# Form implementation generated from reading ui file 'C:\Users\matut\Desktop\Carpetas\APUNTES\DAM-2\DI\Trimestre1\PereiraGutierrez\templates\dialogReport.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialogReports(object):
    """
    Clase de interfaz gráfica para el diálogo de selección de informes.

    Esta clase define la interfaz gráfica para seleccionar el tipo de informe a imprimir.

    """
    def setupUi(self, dialogReports):
        """
        Configura la interfaz gráfica del diálogo de selección de informes.

        :param dialogReports: Ventana del diálogo de selección de informes.
        :type dialogReports: QtWidgets.QDialog

        """
        dialogReports.setObjectName("dialogReports")
        dialogReports.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        dialogReports.resize(400, 251)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/coche2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dialogReports.setWindowIcon(icon)
        dialogReports.setStyleSheet("@font-face {\n"
"font-family: \"Poppins\";\n"
"src: url(resources.qrc/fonts/Poppins/Poppins-Bold.ttf);\n"
"}\n"
"\n"
"QWidget{font-family: \"Poppins\";\n"
"color:white;\n"
"letter-spacing: 1px; }\n"
"\n"
"\n"
"QPushButton{\n"
"padding:5px;\n"
"color:#FFFFFF;\n"
"background-color: #51007A;\n"
"border:none;\n"
"border-radius: 10%;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"background-color: #7E4EAA;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: #330046;\n"
"}\n"
"\n"
"QRadioButton {\n"
"color:#51007A;\n"
"background-color: white;\n"
"}\n"
"\n"
"#frameRbtInformes{\n"
" border-radius: 30%;\n"
" background-color:white;\n"
"}")
        dialogReports.setModal(True)
        self.frame = QtWidgets.QFrame(parent=dialogReports)
        self.frame.setGeometry(QtCore.QRect(112, 200, 176, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnOK = QtWidgets.QPushButton(parent=self.frame)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout.addWidget(self.btnOK)
        self.btnCancel = QtWidgets.QPushButton(parent=self.frame)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.frameRbtInformes = QtWidgets.QFrame(parent=dialogReports)
        self.frameRbtInformes.setGeometry(QtCore.QRect(85, 15, 231, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameRbtInformes.sizePolicy().hasHeightForWidth())
        self.frameRbtInformes.setSizePolicy(sizePolicy)
        self.frameRbtInformes.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameRbtInformes.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameRbtInformes.setObjectName("frameRbtInformes")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameRbtInformes)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rbtFac = QtWidgets.QRadioButton(parent=self.frameRbtInformes)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.rbtFac.setFont(font)
        self.rbtFac.setChecked(True)
        self.rbtFac.setObjectName("rbtFac")
        self.verticalLayout.addWidget(self.rbtFac)
        self.rbtClientes = QtWidgets.QRadioButton(parent=self.frameRbtInformes)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.rbtClientes.setFont(font)
        self.rbtClientes.setObjectName("rbtClientes")
        self.verticalLayout.addWidget(self.rbtClientes)
        self.rbtDrivers = QtWidgets.QRadioButton(parent=self.frameRbtInformes)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.rbtDrivers.setFont(font)
        self.rbtDrivers.setObjectName("rbtDrivers")
        self.verticalLayout.addWidget(self.rbtDrivers)

        self.retranslateUi(dialogReports)
        QtCore.QMetaObject.connectSlotsByName(dialogReports)

    def retranslateUi(self, dialogReports):
        """
        Traduce los textos de la interfaz gráfica del diálogo de selección de informes.

        :param dialogReports: Ventana del diálogo de selección de informes.
        :type dialogReports: QtWidgets.QDialog

        """
        _translate = QtCore.QCoreApplication.translate
        dialogReports.setWindowTitle(_translate("dialogReports", "CarTeis"))
        self.btnOK.setText(_translate("dialogReports", "Aceptar"))
        self.btnCancel.setText(_translate("dialogReports", "Cancelar"))
        self.rbtFac.setText(_translate("dialogReports", "Imprimir facturas"))
        self.rbtClientes.setText(_translate("dialogReports", "Imprimir clientes"))
        self.rbtDrivers.setText(_translate("dialogReports", "Imprimir conductores"))
