# Form implementation generated from reading ui file '.\templates\calendar.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgCalendar(object):
    """
    Clase de interfaz gráfica para el diálogo de calendario.

    Esta clase define la interfaz gráfica para mostrar un calendario.

    """
    def setupUi(self, dlgCalendar):
        """
        Configura la interfaz gráfica del diálogo de calendario.

        :param dlgCalendar: Ventana del diálogo de calendario.
        :type dlgCalendar: QtWidgets.QDialog

        """
        dlgCalendar.setObjectName("dlgCalendar")
        dlgCalendar.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dlgCalendar.resize(400, 349)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/coche2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgCalendar.setWindowIcon(icon)
        dlgCalendar.setAutoFillBackground(False)
        dlgCalendar.setStyleSheet("")
        dlgCalendar.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(dlgCalendar)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.Calendar = QtWidgets.QCalendarWidget(parent=dlgCalendar)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.Calendar.setFont(font)
        self.Calendar.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.Calendar.setStyleSheet("QCalendarWidget{\n"
"font-family: \"Poppins\";\n"
"color: cyan;\n"
"letter-spacing: 1px;\n"
"background-color: #00ff00;\n"
"}")
        self.Calendar.setObjectName("Calendar")
        self.gridLayout.addWidget(self.Calendar, 0, 0, 1, 1)

        self.retranslateUi(dlgCalendar)
        QtCore.QMetaObject.connectSlotsByName(dlgCalendar)

    def retranslateUi(self, dlgCalendar):
        """
        Traduce los textos de la interfaz gráfica del diálogo de calendario.

        :param dlgCalendar: Ventana del diálogo de calendario.
        :type dlgCalendar: QtWidgets.QDialog

        """
        _translate = QtCore.QCoreApplication.translate
        dlgCalendar.setWindowTitle(_translate("dlgCalendar", "Calendario"))
