# Form implementation generated from reading ui file 'C:\Users\matut\Desktop\Carpetas\APUNTES\DAM-2\DI\Trimestre1\PereiraGutierrez\templates\salir.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSalir(object):
    """
    Clase que define la interfaz de usuario del diálogo de confirmación para salir de la aplicación.
    Esta clase se encarga de configurar los elementos visuales del diálogo y gestionar sus traducciones.
    """
    def setupUi(self, dlgSalir):
        """
        Configura la interfaz de usuario del diálogo para salir.

        :param dlgSalir: Referencia al diálogo para salir.
        """
        dlgSalir.setObjectName("dlgSalir")
        dlgSalir.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dlgSalir.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img/coche2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgSalir.setWindowIcon(icon)
        dlgSalir.setModal(True)
        self.frameSalir = QtWidgets.QFrame(parent=dlgSalir)
        self.frameSalir.setGeometry(QtCore.QRect(70, 50, 261, 191))
        self.frameSalir.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frameSalir.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameSalir.setObjectName("frameSalir")
        self.btnCancelarSalir = QtWidgets.QPushButton(parent=self.frameSalir)
        self.btnCancelarSalir.setGeometry(QtCore.QRect(150, 120, 75, 23))
        self.btnCancelarSalir.setObjectName("btnCancelarSalir")
        self.lblDeseaSalir = QtWidgets.QLabel(parent=self.frameSalir)
        self.lblDeseaSalir.setGeometry(QtCore.QRect(70, 50, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblDeseaSalir.setFont(font)
        self.lblDeseaSalir.setObjectName("lblDeseaSalir")
        self.btnAceptarSalir = QtWidgets.QPushButton(parent=self.frameSalir)
        self.btnAceptarSalir.setGeometry(QtCore.QRect(40, 120, 75, 23))
        self.btnAceptarSalir.setObjectName("btnAceptarSalir")

        self.retranslateUi(dlgSalir)
        QtCore.QMetaObject.connectSlotsByName(dlgSalir)

    def retranslateUi(self, dlgSalir):
        """
        Traduce los textos de la interfaz de usuario del diálogo para salir.

        :param dlgSalir: Referencia al diálogo para salir.
        """
        _translate = QtCore.QCoreApplication.translate
        dlgSalir.setWindowTitle(_translate("dlgSalir", "Salir"))
        self.btnCancelarSalir.setText(_translate("dlgSalir", "Cancelar"))
        self.lblDeseaSalir.setText(_translate("dlgSalir", "¿Desea Salir?"))
        self.btnAceptarSalir.setText(_translate("dlgSalir", "Aceptar"))
