# Form implementation generated from reading ui file 'C:\Users\matut\Desktop\Carpetas\APUNTES\DAM-2\DI\Trimestre1\PereiraGutierrez\templates\slider.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SliderWidget(object):
    """
    Clase que define la interfaz de usuario para un widget de control deslizante.
    Este widget consta de un control deslizante horizontal con etiquetas de imagen para representar diferentes estados.
    """
    def setupUi(self, SliderWidget):
        """
        Configura la interfaz de usuario del widget de control deslizante.

        :param SliderWidget: Referencia al widget de control deslizante.
        """
        SliderWidget.setObjectName("SliderWidget")
        SliderWidget.resize(320, 176)
        SliderWidget.setStyleSheet("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=SliderWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 60, 160, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 20, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(20, 20))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/img/sol.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(30, 30))
        self.horizontalSlider.setMaximumSize(QtCore.QSize(30, 30))
        self.horizontalSlider.setStyleSheet("")
        self.horizontalSlider.setMaximum(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(18, 18))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/img/img/luna.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)

        self.retranslateUi(SliderWidget)
        QtCore.QMetaObject.connectSlotsByName(SliderWidget)

    def retranslateUi(self, SliderWidget):
        """
        Traduce los textos de la interfaz de usuario del widget de control deslizante.

        :param SliderWidget: Referencia al widget de control deslizante.
        """
        _translate = QtCore.QCoreApplication.translate
        SliderWidget.setWindowTitle(_translate("SliderWidget", "Form"))
